#services:
#  catalogdb:
#    container_name: catalogdb
#    environment:
#      - POSTGRES_USER=postgres
#      - POSTGRES_PASSWORD=postgres
#      - POSTGRES_DB=CatalogDb
#    restart: always
#    ports:
#      - "5432:5432"
#    volumes:
#      - postgres_catalog:/var/lib/postgresql/data
#
#
#  catalog.api:
#    environment:
#      - ASPNETCORE_ENVIRONMENT=Development
#      - ConnectionStrings__Database=Server=catalogdb;Port=5432;Database=CatalogDb;Username=postgres;Password=postgres
#      - ASPNETCORE_HTTP_PORT=8080
#      - ASPNETCORE_HTTPS_PORT=8081
#    depends_on:
#      - catalogdb
#    ports:
#      - "6000:8080"
#      - "6060:8081"
#    volumes:
#      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
#      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro



version: '3.4'

services:
  catalogdb:
    container_name: catalogdb
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=CatalogDb
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_catalog:/var/lib/postgresql/data
        
  
  basketdb:
    container_name: basketdb
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=BasketDb
    restart: always
    ports:
      - "5433:5432"
    volumes:
      - postgres_basket:/var/lib/postgresql/data
        
  distributedcache:
    container_name: distributedcache
    restart: always
    ports:
      - "6379:6379"

  catalog.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__Database=Server=catalogdb;Port=5432;Database=CatalogDb;Username=postgres;Password=postgres
      - ASPNETCORE_HTTP_PORT=8080
      - ASPNETCORE_HTTPS_PORT=8443
      - ASPNETCORE_URLS=https://+:8443;http://+:8080
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/app/ssl-certs/your_certificate.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password=c3e6r9t2
    depends_on:
      - catalogdb
    ports:
      - "6000:8080"
      - "6060:8443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
      - ./ssl-certs:/app/ssl-certs:ro # Mount the directory with SSL certificates

  basket.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__Database=Server=basketdb;Port=5432;Database=BasketDb;Username=postgres;Password=postgres
      - ConnectionStrings__Redis=distributedcache:6379
      - GrpcConfigs__DiscountUrl=https://discount.grpc:8443
      - ASPNETCORE_HTTP_PORT=8080
      - ASPNETCORE_HTTPS_PORT=8443
      - ASPNETCORE_URLS=https://+:8443;http://+:8080
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/app/ssl-certs/your_certificate.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password=c3e6r9t2
    depends_on:
      - discount.grpc
      - basketdb
      - distributedcache
    ports:
      - "6001:8080"
      - "6061:8443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
      - ./ssl-certs:/app/ssl-certs:ro # Mount the directory with SSL certificates
      
  discount.grpc:
    environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - ASPNETCORE_HTTP_PORT=8080
        - ASPNETCORE_HTTPS_PORT=8443
        - ASPNETCORE_URLS=https://+:8443;http://+:8080
        - ASPNETCORE_Kestrel__Certificates__Default__Path=/app/ssl-certs/your_certificate.pfx
        - ASPNETCORE_Kestrel__Certificates__Default__Password=c3e6r9t2
        - ConnectionStrings__Database=Data Source=discountdb;
    ports:
      - "6002:8080"
      - "6062:8443"
    volumes:
        - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
        - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
        - ./ssl-certs:/app/ssl-certs:ro # Mount the directory with SSL certificate
