#services:
#  catalogdb:
#    container_name: catalogdb
#    environment:
#      - POSTGRES_USER=postgres
#      - POSTGRES_PASSWORD=postgres
#      - POSTGRES_DB=CatalogDb
#    restart: always
#    ports:
#      - "5432:5432"
#    volumes:
#      - postgres_catalog:/var/lib/postgresql/data
#
#
#  catalog.api:
#    environment:
#      - ASPNETCORE_ENVIRONMENT=Development
#      - ConnectionStrings__Database=Server=catalogdb;Port=5432;Database=CatalogDb;Username=postgres;Password=postgres
#      - ASPNETCORE_HTTP_PORT=8080
#      - ASPNETCORE_HTTPS_PORT=8081
#    depends_on:
#      - catalogdb
#    ports:
#      - "6000:8080"
#      - "6060:8081"
#    volumes:
#      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
#      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro



version: '3.4'

services:
  catalogdb:
    container_name: catalogdb
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=CatalogDb
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_catalog:/var/lib/postgresql/data

  catalog.api:
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__Database=Server=catalogdb;Port=5432;Database=CatalogDb;Username=postgres;Password=postgres
      - ASPNETCORE_HTTP_PORT=8080
      - ASPNETCORE_HTTPS_PORT=8443
      - ASPNETCORE_URLS=https://+:8443;http://+:8080
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/app/ssl-certs/your_certificate.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password=c3e6r9t2
    depends_on:
      - catalogdb
    ports:
      - "6000:8080"
      - "6060:8443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
      - ./ssl-certs:/app/ssl-certs:ro # Mount the directory with SSL certificates

volumes:
  postgres_catalog:
